name: Run Tests on Pull Request to Develop

on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Set environment variable for deployed backend
      - name: Set deployed backend URL
        run: echo "CYPRESS_BASE_URL=https://test-center-afwv.onrender.com" >> $GITHUB_ENV

      # Run Cypress tests
      - name: Run tests
        env:
          CYPRESS_BASE_URL: ${{ env.CYPRESS_BASE_URL }}
        run: npm run test