name: Run Tests on Pull Request to Develop

on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the server
      - name: Build server
        run: npm run build

      # Start the server
      - name: Start the server
        run: npm run start &
        env:
          NODE_ENV: test

      # Wait for the server to be ready
      - name: Wait for server to be ready
        run: npx wait-on http://localhost:3001

      # Run Cypress tests
      - name: Run tests
        run: npm run test